const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  ADD_CART_TO_FIRESTORE_START: "ADD_CART_TO_FIRESTORE_START",
  FETCH_CART_ITEMS_FROM_FIRESTORE_START:
    "FETCH_CART_ITEMS_FROM_FIRESTORE_START",
  FETCH_CART_ITEMS_FROM_FIRESTORE_SUCCESS:
    "FETCH_CART_ITEMS_FROM_FIRESTORE_SUCCESS",
  FETCH_CART_ITEMS_FROM_FIRESTORE_FAILURE:
    "FETCH_CART_ITEMS_FROM_FIRESTORE_FAILURE",
  ADD_CART_TO_ADMIN_START: "ADD_CART_TO_ADMIN_START",
};

export default CartActionTypes;
