const AdminActionTypes = {
  FETCH_ORDERS_FROM_FIRESTORE_START: "FETCH_ORDERS_FROM_FIRESTORE_START",
  FETCH_ORDERS_FROM_FIRESTORE_SUCCESS: "FETCH_ORDERS_FROM_FIRESTORE_SUCCESS",
  FETCH_ORDERS_FROM_FIRESTORE_FAILURE: "FETCH_ORDERS_FROM_FIRESTORE_FAILURE",
};

export default AdminActionTypes;
